# Generated by Django 4.0.6 on 2022-07-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('bill_type', models.CharField(max_length=256)),
                ('value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('is_income', models.BooleanField()),
                ('use_notification', models.BooleanField(blank=True, default=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
