# Generated by Django 4.0.6 on 2022-07-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date',
        ),
        migrations.AddField(
            model_name='bill',
            name='day',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
