# Generated by Django 4.0.6 on 2022-12-04 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_bill_date_bill_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='is_income',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='use_notification',
        ),
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='partials',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[['income', 'Ganho'], ['scheduled_income', 'Ganho agendado'], ['expense', 'Despesa'], ['scheduled_income', 'Despesa agendada']], max_length=256),
        ),
        migrations.AlterField(
            model_name='bill',
            name='day',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
