# Generated by Django 4.0.6 on 2022-12-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_remove_bill_is_income_remove_bill_use_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[['income', 'Ganho'], ['scheduled_income', 'Ganho agendado'], ['expense', 'Despesa'], ['scheduled_expense', 'Despesa agendada']], max_length=256),
        ),
    ]
