# Generated by Django 4.0.6 on 2022-12-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_bill_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[['money', 'Dinheiro'], ['card', 'Cartão'], ['billet', 'Boleto'], ['pix', 'PIX']], default='card', max_length=256),
            preserve_default=False,
        ),
    ]
