# Generated by Django 4.0.6 on 2022-12-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_bill_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
