# Generated by Django 4.0.6 on 2022-12-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_bill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
