# Generated by Django 4.0.6 on 2022-12-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_time',
            field=models.CharField(choices=[['8', '8h'], ['12', '12h'], ['16', '16h'], ['20', '20h']], default='8', max_length=64),
        ),
    ]
